name: Build and Scan

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/build_after_push_action.yml'
      - 'simple-weather-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image for scanning
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          outputs: type=docker,dest=image.tar
          tags: ${{ steps.meta.outputs.tags }}
          cache-from:
            - type=registry,ref=ghcr.io/${{ github.repository }}:cache
            - type=registry,ref=ghcr.io/${{ github.repository }}:cache-${{ matrix.platform }}
          cache-to: type=registry,mode=max,ref=ghcr.io/${{ github.repository }}:cache-${{ matrix.platform }}
          secrets: |
            api_key=${{ secrets.OPENWEATHERMAP_API_KEY }}
      
      - name: Load Docker image for scanning
        run: |
          docker load -i image.tar
          echo "Image loaded successfully."

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
      
      - name: Build and push multi-arch Docker image
        if: ${{ success() }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }},ghcr.io/${{ github.repository }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:cache
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:cache-${{ matrix.platform }}
          cache-to: type=registry,mode=max,ref=ghcr.io/${{ github.repository }}:cache
          secrets: |
            api_key=${{ secrets.OPENWEATHERMAP_API_KEY }}